PropertyManagerMyApp/PropertyManagerMyApp/Controllers/DashboardController.cs
using SuiteLevelWebApp.Models;
using SuiteLevelWebApp.Services;
using SuiteLevelWebApp.Utils;
using System;
using System.Configuration;
using System.Web;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Graph;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http.Results;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SuiteLevelWebApp.Controllers
{
    [Authorize, HandleAdalException]
    public class DashboardController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var sharePointToken = await AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            Dashboard dashboardModel = new Dashboard(sharePointToken);
            var model = await dashboardModel.GetDashboardPropertiesViewModelAsync();
            return View(model);
        }

        public async Task<ActionResult> Property(int id)
        {
            var sharePointToken = await AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            Dashboard dashboardModel = new Dashboard(sharePointToken);
            var model = await dashboardModel.GetDashboardPropertiesViewModelAsync(id);

            return View(model);
        }

        public async Task<ActionResult> InspectionDetails(int id)
        {
            var sharePointToken = await AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            var graphService = await AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);
            Dashboard dashboardModel = new Dashboard(sharePointToken);
            var model = await dashboardModel.GetDashboardInspectionDetailsViewModelAsync(graphService, id, User.Identity.Name);
            if (model == null) return HttpNotFound();
            var accessToken = await AuthenticationHelper.GetGraphAccessTokenAsync();
            TempData["accesstoken"] = accessToken;
            await dashboardModel.CheckSubscriptionAsync(graphService, accessToken);
            return View(model);
        }

        
        [HttpGet]
        public async Task<FileResult> GetPropertyGroupExcelChart(string groupId, string fileId, string title)
        {
            var imageBinary = await ExcelService.GetPropertyExcelWorkbookChartImageAsync(groupId, fileId, title);
            return new FileContentResult(imageBinary, "image/bmp"); ;
        }

        [HttpPost]
        public async Task<ActionResult> ScheduleRepair(ScheduleRepairModel model)
        {
            model.TimeSlotsSelectedValue = DateTime.ParseExact(string.Format("{0} {1}:00", model.TimeSlotsSelectedDateValue, model.TimeSlotsSelectedHoursValue),
                "yyyy-MM-dd HH:mm", null);
            var sharePointToken = AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            var graphService = AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);

            var tasksService = new TasksService(await sharePointToken);
            var dashboardModel = new Dashboard(await sharePointToken);

            await dashboardModel.UpdateRepairScheduleInfoToIncidentAsync(model)
                .ContinueWith(async task => await tasksService.CompleteRepairAssignmentTaskAsync(model.IncidentId));

            await dashboardModel.ScheduleRepairAsync(await graphService, model);
            await dashboardModel.CreateGroupRepairEventAsync(await graphService, model);
            await dashboardModel.CreateO365TaskAsync(await graphService, model);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> AuditRepair(AuditRepairModel model)
        {
            var sharePointToken = await AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            Dashboard dashboardModel = new Dashboard(sharePointToken);

            var tasksService = new TasksService(sharePointToken);
            await tasksService.CompleteRepairApprovalTaskAsync(model);

            if (model.Result == ApprovalResult.Approved)
                await dashboardModel.ApproveRepairAsync(model.IncidentId);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> AnnotateImages(int incidentId)
        {
            var sharePointToken = AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
            var graphService = AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);
            var dashboardService = new Dashboard(await sharePointToken);

            var pageUrl = await dashboardService.AnnotateImagesAsync(await graphService, Server.MapPath("/"), incidentId);
            return Redirect(pageUrl);
        }

        [HttpPost]
        public async Task<ActionResult> UploadFile(UploadFileModel model)
        {
            if (model.File != null)
            {
                var token = AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
                var graphService = AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);

                var dashboardService = new Dashboard(await token);
                await dashboardService.UploadFileAsync(await graphService, model);
            }

            return RedirectToAction("InspectionDetails", new { id = model.IncidentId });
        }

    }
}

PropertyManagerMyApp/PropertyManagerMyApp/Controllers/PhotoController.cs
using Microsoft.SharePoint.Client;
using SuiteLevelWebApp.Utils;
using System.IO;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Graph;
using System;

namespace SuiteLevelWebApp.Controllers
{
    [Authorize, HandleAdalException]
    public class PhotoController : Controller
    {
        [OutputCache(Duration = 600, VaryByParam = "*")]
        public async Task<ActionResult> UserPhoto(string userId)
        {
            try
            {
                GraphServiceClient graphService = await AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);
                var fileStream = await graphService.Users[userId].Photo.Content.Request().GetAsync();
                if(fileStream != null)
                      return File(fileStream, "image/jpeg");
            }
            catch {

            }
            return File(Server.MapPath("/Content/images/DefaultUserPhoto.jpg"), "image/jpeg");
        }

        [OutputCache(Duration = 600, VaryByParam = "*")]
        public async Task<ActionResult> DriveItemThumbnail(string groupId, string fileId)
        {
            try
            {
                var graphService = await AuthenticationHelper.GetGraphServiceAsync(AADAppSettings.GraphResourceUrl);
                var thumbnails = await graphService.Groups[groupId].Drive.Items[fileId].Thumbnails["0"].Request().GetAsync();
                var uri = thumbnails.Medium.Url;
                var token = AuthenticationHelper.GetAccessTokenAsync(AppSettings.DemoSiteServiceResourceId);
                var request = (HttpWebRequest)HttpWebRequest.Create(uri);

                request.Method = "GET";
                request.Headers.Add("Authorization", "Bearer " + await token);


                var response = (HttpWebResponse)(await request.GetResponseAsync());
                if (response.StatusCode == HttpStatusCode.OK)
                    return File(response.GetResponseStream(), response.ContentType);
            }
            catch { }

            throw new HttpException(404, "File not found");
        }

        [OutputCache(Duration = 600, VaryByParam = "*")]
        public async Task<ActionResult> GetPhoto(string url)
        {
            try
            {
                using (var clientContext = await AuthenticationHelper.GetDemoSiteClientContextAsync())
                {
                    Match match = (new Regex(@"(?<=\.)(\w*)")).Match(url);
                    string contentType = string.Format("image/{0}", match.Captures[match.Captures.Count - 1].Value);

                    Microsoft.SharePoint.Client.File file = clientContext.Web.GetFileByServerRelativeUrl(url);
                    clientContext.Load(file);
                    clientContext.ExecuteQuery();

                    ClientResult<Stream> clientResult = file.OpenBinaryStream();
                    clientContext.ExecuteQuery();

                    using (Stream stream = clientResult.Value)
                    {
                        byte[] data = new byte[stream.Length];
                        stream.Read(data, 0, data.Length);
                        return File(data, contentType);
                    }
                }
            }
            catch
            { }

            throw new HttpException(404, "File not found");
        }
    }
}

PropertyManagerMyApp/PropertyManagerMyApp/Views/Dashboard/Inspection.cshtml
@model DashboardInspectionDetailsViewModel

<h1>Inspection</h1>
<div class="bg-white inspection-details">
    <div class="content-block">
        <div class="fs-smaller">Photos</div>
        <div class="photo-lists">
            <ul class="clear">
                @foreach (var item in Model.roomInspectionPhotos.Where(r => r.sl_incidentIDId != null && r.sl_incidentIDId == Model.incidentId))
                {
                    <li>
                        <div class="crop">
                            <img src="@item.sl_roomID.imgUrl" />
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
    @if (Model.viewName == "ScheduleRepair")
    {
        <div class="content-block">
            <button class="pull-left fs-smaller" id="annotateImagesButton" type="button" data-form-method="POST" data-form-target="_blank"
                    data-form-action="@Url.Action("AnnotateImages", new { incidentId = Model.incidentId })" @(Model.bAnnotateImage ? "": "disabled")>
                Annotate images
            </button>
        </div>
    }

    <div class="content-block videos">
        <div class="fs-smaller">Videos</div>
        <ul>
            @foreach (var item in Model.videos)
            {
                <li>
                    <a href="@item.YammerObjectUrl" target="_blank">
                        <img src="@item.ThumbnailUrl" />
                    </a>
                </li>
            }
        </ul>
    </div>
    <div class="bottom-bar">
        <a href="javascript:popupwindow('.inspection-comments-window')" class="f-teal fs-smaller ff-semilight">
            <i class="icon-appbardrawpencil fs-reg"></i>
            See inspection comments
        </a>
        <a href="javascript:popupwindow('.incident-window')" class="f-teal fs-smaller ff-semilight">
            <i class="icon-appbartools fs-large"></i>
            See incident details
        </a>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        (function initRoomControl() {
            var count = $('.img-container img').length;
            if (count <= 3) {
                $('.img-scroll-control .left-arrow, .img-scroll-control .right-arrow').css('visibility', 'hidden');
                return;
            }
            else {
                $('.img-list').width(count * 153 + (count - 1) * 20);
                $('.img-scroll-control .left-arrow').click(function () {
                    var left = parseInt($('.img-list').css('left')),
                        count = $('.img-container img').length;
                    if (left < 0) {
                        $('.img-list').animate({
                            left: left + 173
                        }, 500);
                    }
                });
                $('.img-scroll-control .right-arrow').click(function () {
                    var left = parseInt($('.img-list').css('left')),
                        count = $('.img-container img').length;
                    if (left > (count - 3) * -173) {
                        $('.img-list').animate({
                            left: left - 173
                        }, 500);
                    }
                });
            }
        })();
        $('#annotateImagesButton').click(function () {
            var button = $(this);
            $('<form>')
                .attr('method', button.attr('data-form-method'))
                .attr('target', button.attr('data-form-target'))
                .attr('action', button.attr('data-form-action'))
                .appendTo("body")
                .submit()
                .remove();
            button.attr("disabled", "disabled");
        });
    });
    function popupwindow(type) {
        var winHeight = $(window).height();
        var bodyHeight = $('body').outerHeight();

        $('.popup-window').height(bodyHeight > winHeight ? bodyHeight : winHeight);
        $('.popup-window .content-area > div').hide();
        $('.popup-window').show();
        $('.popup-window').find(type).show();

        var contentHeight = $('.popup-window > .content-area').outerHeight();
        $(window).scrollTop(0);
        if (winHeight > contentHeight) {
            $('.popup-window > .content-area').css("top", (winHeight - contentHeight) / 2 + $(window).scrollTop() - 100); /* minus the height of margin top 100 of popup content area */
        }
        else {
            $('.popup-window > .content-area').css("top", "10px");
        }

    }
</script>

PropertyManagerMyApp/PropertyManagerMyApp/Views/Dashboard/RepairApproved.cshtml
@model DashboardInspectionDetailsViewModel

<h1>Repair Approved</h1>
<form>
    <div class="dispatcher-comments">
        <div class="content-row">
            <label>
                Dispatcher comments
            </label>
            @Html.TextAreaFor(m => m.incident.sl_dispatcherComments, new { @readonly = "readonly" })
        </div>
    </div>

    <div class="content-row">
        @Html.Partial("Inspection", Model)
    </div>

    <div class="content-row">
        <div class="section">
            <h1>Repair</h1>
            <div class="bg-white repair-details">
                <div class="content-block">
                    <div class="fs-smaller">Photos</div>
                    <div class="photos-lists">
                        <ul class="clear">
                            @foreach (var item in Model.repairPhotos)
                            {
                                <li>
                                    <div class="crop">
                                        <img src="@item.imgUrl" />
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="bottom-bar">
                    <a href="javascript:popupwindow('.repair-comments-window')" class="f-teal fs-smaller ff-semilight">
                        <i class="icon-appbardrawpencil fs-reg"></i>
                        See repair comments
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

PropertyManagerMyApp/PropertyManagerMyApp/Views/Dashboard/RepairComplete.cshtml
@model DashboardInspectionDetailsViewModel

<h1>Repair Complete</h1>
@using (Html.BeginForm("AuditRepair", "Dashboard", FormMethod.Post))
{
    @Html.HiddenFor(m => m.incidentId)
    <form>
        <div class="dispatcher-comments">
            <div class="content-row">
                <label>
                    Dispatcher comments
                </label>
                @Html.TextAreaFor(m => m.incident.sl_dispatcherComments, new { @readonly = "readonly" })

            </div>
        </div>
        <div class="content-row">
            @Html.Partial("Inspection", Model)
        </div>
        <div class="content-row">
            <h1>Repair</h1>
            <div class="bg-white repair-details">
                <div class="content-block">
                    <div class="fs-smaller">Photos</div>
                    <div class="photos-lists">
                        <ul class="clear">
                            @foreach (var item in Model.repairPhotos)
                            {
                                <li>
                                    <div class="crop">
                                        <img src="@item.imgUrl" />
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="bottom-bar">
                    <a href="javascript:popupwindow('.repair-comments-window')" class="f-teal fs-smaller ff-semilight">
                        <i class="icon-appbardrawpencil fs-reg"></i>
                        See repair comments
                    </a>
                </div>
            </div>
            <div class="form-bottom-button">
                <button class="button-large pull-right" name="result" value="Approved">Approve repair</button>
                <button class="secondary-btn button-large pull-right" name="result" value="Rejected">Reject repair</button>
            </div>
        </div>
    </form>
}

PropertyManagerMyApp/PropertyManagerMyApp/Views/Dashboard/RepairInProgress.cshtml
@model SuiteLevelWebApp.Models.DashboardInspectionDetailsViewModel

<h1>Repair in Progress</h1>
<form>
    <div class="dispatcher-comments">
        <div class="content-row">
            <label>
                Dispatcher comments
            </label>
            @Html.TextAreaFor(m => m.incident.sl_dispatcherComments, new { @readonly = "readonly" })

        </div>
    </div>
    <div class="content-row">
            @Html.Partial("Inspection", Model)
    </div>
</form>

PropertyManagerMyApp/PropertyManagerMyApp/Views/Dashboard/ScheduleRepair.cshtml
@using Newtonsoft.Json;
@model DashboardInspectionDetailsViewModel

@{
    var repairPeopleList = Model.repairPeople.Select(x => new { label = x.DisplayName, value = x.Mail }).ToList();
    string repairPeoplejson = JsonConvert.SerializeObject(repairPeopleList);
}

<h1>Schedule a repair</h1>
@using (Html.BeginForm("ScheduleRepair", "Dashboard", FormMethod.Post))
{
    @Html.HiddenFor(m => m.incidentId)
    <form>
        <div class="content-row">
            @Html.Partial("Inspection", Model)
        </div>
        <div class="content-row">
            <label>Dispatcher comments</label>
            @Html.TextArea("dispatcherComments")
        </div>
        <div class="schedule-repair">
            <div class="content-row">
                @Html.Hidden("repairPeopleSelectedValue")
                <label for="repairPeopleSelectedValue">Repair person:</label>
                <input id="repairPeople-autocomplete-input">
                <span class="error-message">*</span>
                <span id="repairPeopleImg"></span>
            </div>
            <div class="content-row">
                <label class="pull-left">Date:</label>
                <div class="fs-smaller">
                    @System.DateTime.Now.AddDays(1).ToShortDateString()
                </div>
            </div>
            <div class="content-row">
                <label for="TimeSlots">Time:</label>
                @Html.Hidden("timeSlotsSelectedValue")
                @Html.Hidden("timeSlotsSelectedDateValue")
                @Html.Hidden("timeSlotsSelectedHoursValue")
                <select id="TimeSlots">
                    <option>No Available Time Slots</option>
                </select>
                <span class="error-message">*</span>
            </div>
            <div class="content-row with-button">
                <button class="pull-right button-large" id="btn_scheduleRepair">Schedule Repair</button>
            </div>
        </div>
    </form>
    <script>
        $(function () {

            $('#TimeSlots').selectmenu();

            function initTimeSlots() {
                var sel = $('#TimeSlots');
                if (sel.length > 0) {
                    var localDate = getTomorrowDateString();
                    $("#timeSlotsSelectedDateValue").val(localDate)
                    $.getJSON("/O365Calendar/GetAvailableTimeSlots?localDate=" + localDate +"&userEmail="+$( "#repairPeopleSelectedValue" ).val(), function (data) {
                        if (data.length > 0) {
                            sel.html('').append("<option selected value='0'>Available Time Slots</option>");
                            for (var i = 0; i < data.length; i++) {
                                sel.append("<option value=" + data[i].Start + ">" + data[i].Value + "</option>");
                            }
                            sel.change(function () {
                                if ($(this).val() > 0) {
                                    $("#timeSlotsSelectedHoursValue").val($(this).val())
                                    
                                }
                            });
                        }
                        else {
                            sel.html('').append("<option selected value='0'>No Available Time Slots</option>");
                        }
                        $('#TimeSlots').selectmenu('refresh');
                    });
                }
            }


            $('#btn_scheduleRepair').click(function (event) {
                $('.error-message').hide();
                if ($('#repairPeopleSelectedValue').val() == 0) {
                    event.preventDefault();
                    $('.error-message').eq(0).show();
                }
                if ($('#TimeSlots').val() == 0) {
                    event.preventDefault();
                    $('.error-message').eq(1).show();
                }
                else {
                    var now = new Date(), tomorrow = (now.setDate(now.getDate() + 1), new Date(now.toDateString()));
                    $("#timeSlotsSelectedHoursValue").val($('#TimeSlots').val())
                }
            });

            //people auto complete
            var repairPeopleArrays = @Html.Raw(repairPeoplejson);
            $("#repairPeople-autocomplete-input").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "https://graph.microsoft.com/beta/me/people?$filter=sources/any(s:s/type eq 'Directory')",
                        headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer '+'@TempData["accesstoken"]' },
                        dataType: "json",
                        data: {
                            $search: '"'+ request.term +'"'
                        },
                        success: function( data ) {
                            if(data != null && data.value != null){
                                response( getPeopleInRepairGroup(data.value) );
                            }
                        }
                    });
                },
                minLength: 1,
                focus: function( event, ui ) {
                    $( "#repairPeopleAuto" ).val( ui.item.label );
                    return false;
                },
                select: function( event, ui ) {
                    $( "#repairPeople-autocomplete-input" ).val( ui.item.label );
                    $( "#repairPeopleSelectedValue" ).val( ui.item.value );

                    var repairImg = '<img  class="ui-icon" src="' + '@Url.Action("UserPhoto", "Photo")?userId=' + ui.item.value+'">'
                    $("#repairPeopleImg").html(repairImg)
                    $('#TimeSlots').html("<option>Loading...</option>");
                    $('#TimeSlots').selectmenu('refresh');
                    initTimeSlots()
                    return false;
                }
            })
            .autocomplete("instance")._renderItem = function( ul, item ) {
                return $( "<li>" )
                    .append( "<a>" + item.label +"</a>" )
                    .appendTo( ul );
            };
            $("#repairPeople-autocomplete-input").on( "autocompletechange", function(event,ui) {
                if(repairPeopleArrays.map(function(e) { return e.value; }).indexOf($( "#repairPeopleSelectedValue" ).val()) == -1){
                    $('#TimeSlots').html("<option selected value='0'>No Available Time Slots</option>");
                    $('#TimeSlots').selectmenu('refresh');
                }
            });
            function getPeopleInRepairGroup(peopleArray){
                var retArray = new Array();
                for(var peopleIndex in peopleArray){
                    var displayName = peopleArray[peopleIndex].displayName;
                    var emailAddress = peopleArray[peopleIndex].emailAddresses[0].address
                    for(var repairPeopleIndex in repairPeopleArrays){
                        if(emailAddress == repairPeopleArrays[repairPeopleIndex].value){
                            retArray.push(repairPeopleArrays[repairPeopleIndex])
                        }
                    }
                }
                return retArray;
            }
            function getTomorrowDateString(){
                var now = new Date(), tomorrow = new Date();
                tomorrow.setDate(now.getDate()+1);
                var month = '' + (tomorrow.getMonth() + 1), day = '' + tomorrow.getDate();
                if(month.length < 2) month = '0'+ month;
                if(day.length < 2) day = '0'+ day;

                var localDate = (tomorrow.getFullYear() + "-" + month +"-" + day);
                return localDate;
            }

        });
    </script>
}